In [51]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("data_icaller.csv")

In [3]:
df.head()

phone  type  in_contact  duration  call_to  call_in  call_to_miss  \
0  84989082183   270          82       129        4        9            28   
1     8.42E+11  2105          29     42620      485       86           424   
2     8.43E+11  2019         102     44968      511      214           224   
3  84965303997   580          77      6106       57       26            85   
4  84979169738    23           9       455        1        5             0   

   call_in_miss  duration_call_to  duration_call_in  duration_call_to_miss  \
0            41                10               119                      0   
1            44             35170              4811                   2639   
2           102             27173             16562                   1233   
3            54               245              5852                      9   
4             3                97               358                      0   

   duration_call_in_miss  sum_call  Spam  Unnamed: 14  
0                      0        82     1          NaN  
1                      0      1039     1          NaN  
2                      0      1051     1          NaN  
3                      0       222     1          NaN  
4                      0         9     1          NaN

In [6]:
df=df.drop(["phone","duration_call_to","duration_call_in","duration_call_to_miss","duration_call_in_miss","sum_call"],axis=1)

In [7]:
df.head()

type  in_contact  duration  call_to  call_in  call_to_miss  call_in_miss  \
0   270          82       129        4        9            28            41   
1  2105          29     42620      485       86           424            44   
2  2019         102     44968      511      214           224           102   
3   580          77      6106       57       26            85            54   
4    23           9       455        1        5             0             3   

   Spam  Unnamed: 14  
0     1          NaN  
1     1          NaN  
2     1          NaN  
3     1          NaN  
4     1          NaN

In [9]:
df.shape

(1200, 9)

In [12]:
df.sum()

type              83134.0
in_contact         8579.0
duration        1105497.0
call_to           12205.0
call_in            8995.0
call_to_miss      12973.0
call_in_miss       3505.0
Spam                600.0
Unnamed: 14           0.0
dtype: float64

In [19]:
X = df.iloc[:, :-2].values

In [20]:
X

array([[  270,    82,   129, ...,     9,    28,    41],
       [ 2105,    29, 42620, ...,    86,   424,    44],
       [ 2019,   102, 44968, ...,   214,   224,   102],
       ...,
       [    2,     1,    45, ...,     1,     0,     0],
       [    1,     0,    19, ...,     0,     0,     0],
       [    6,     0,     0, ...,     0,     2,     0]], dtype=int64)

In [22]:
y = df.iloc[:, 7].values

In [23]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [26]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1], d

In [40]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[134  20]
 [ 25 121]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.87      0.86       154
           1       0.86      0.83      0.84       146

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

Accuracy: 0.85


In [43]:
from sklearn.ensemble import RandomForestClassifier
model_test = RandomForestClassifier(n_estimators = 10)
model_test.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [44]:
y_pred1 = classifier.predict(X_test)

In [45]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result_0 = confusion_matrix(y_test, y_pred1)
print("Confusion Matrix:")
print(result_0)
result_1 = classification_report(y_test, y_pred1)
print("Classification Report:",)
print (result_1)
result_2 = accuracy_score(y_test,y_pred1)
print("Accuracy:",result_2)

Confusion Matrix:
[[134  20]
 [ 25 121]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.87      0.86       154
           1       0.86      0.83      0.84       146

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

Accuracy: 0.85


In [67]:
df.to_csv('data_spam_call.csv', index=False)

In [53]:
for i in df.index:
    if(df['call_in'][i].value + df['call_to'][i].values)
    df['avg_drt']=df['duration']/(df['call_in']+df['call_to'])

In [55]:
df['avg_drt'][3]

73.56626506024097

In [56]:
df['avg_drt'].isnull().sum()

232

In [58]:
df['avg_drt'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
1195    False
1196    False
1197    False
1198    False
1199     True
Name: avg_drt, Length: 1200, dtype: bool

In [65]:
for i in df.index:
    if(df['avg_drt'][i]=='False'):
        df['avg_drt'][i]=0

In [68]:
df['avg_drt']

232

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
type            1200 non-null int64
in_contact      1200 non-null int64
duration        1200 non-null int64
call_to         1200 non-null int64
call_in         1200 non-null int64
call_to_miss    1200 non-null int64
call_in_miss    1200 non-null int64
Spam            1200 non-null int64
Unnamed: 14     0 non-null float64
avg_drt         968 non-null float64
dtypes: float64(2), int64(8)
memory usage: 93.9 KB


In [70]:
df.fillna(0, inplace = True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
type            1200 non-null int64
in_contact      1200 non-null int64
duration        1200 non-null int64
call_to         1200 non-null int64
call_in         1200 non-null int64
call_to_miss    1200 non-null int64
call_in_miss    1200 non-null int64
Spam            1200 non-null int64
Unnamed: 14     1200 non-null float64
avg_drt         1200 non-null float64
dtypes: float64(2), int64(8)
memory usage: 93.9 KB


In [72]:
df


type  in_contact  duration  call_to  call_in  call_to_miss  \
0      270          82       129        4        9            28   
1     2105          29     42620      485       86           424   
2     2019         102     44968      511      214           224   
3      580          77      6106       57       26            85   
4       23           9       455        1        5             0   
...    ...         ...       ...      ...      ...           ...   
1195     6           0        16        2        0             0   
1196     1           1        16        1        0             0   
1197     2           1        45        0        1             0   
1198     1           0        19        1        0             0   
1199     6           0         0        0        0             2   

      call_in_miss  Spam  Unnamed: 14    avg_drt  
0               41     1          0.0   9.923077  
1               44     1          0.0  74.640981  
2              102     1          0.0  62.024828  
3               54     1          0.0  73.566265  
4                3     1          0.0  75.833333  
...            ...   ...          ...        ...  
1195             1     0          0.0   8.000000  
1196             0     0          0.0  16.000000  
1197             0     0          0.0  45.000000  
1198             0     0          0.0  19.000000  
1199             0     0          0.0   0.000000  

[1200 rows x 10 columns]

In [77]:
df.drop(['duration'], axis=1)

type  in_contact  call_to  call_in  call_to_miss  call_in_miss  Spam  \
0      270          82        4        9            28            41     1   
1     2105          29      485       86           424            44     1   
2     2019         102      511      214           224           102     1   
3      580          77       57       26            85            54     1   
4       23           9        1        5             0             3     1   
...    ...         ...      ...      ...           ...           ...   ...   
1195     6           0        2        0             0             1     0   
1196     1           1        1        0             0             0     0   
1197     2           1        0        1             0             0     0   
1198     1           0        1        0             0             0     0   
1199     6           0        0        0             2             0     0   

      Unnamed: 14    avg_drt  
0             0.0   9.923077  
1             0.0  74.640981  
2             0.0  62.024828  
3             0.0  73.566265  
4             0.0  75.833333  
...           ...        ...  
1195          0.0   8.000000  
1196          0.0  16.000000  
1197          0.0  45.000000  
1198          0.0  19.000000  
1199          0.0   0.000000  

[1200 rows x 9 columns]

In [85]:
new_df=df[["type","in_contact","call_to","call_in","call_to_miss","call_in_miss","avg_drt","Spam"]]

In [86]:
new_df.head()

type  in_contact  call_to  call_in  call_to_miss  call_in_miss    avg_drt  \
0   270          82        4        9            28            41   9.923077   
1  2105          29      485       86           424            44  74.640981   
2  2019         102      511      214           224           102  62.024828   
3   580          77       57       26            85            54  73.566265   
4    23           9        1        5             0             3  75.833333   

   Spam  
0     1  
1     1  
2     1  
3     1  
4     1

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [88]:
from sklearn.ensemble import RandomForestClassifier
model_test = RandomForestClassifier(n_estimators = 10)
model_test.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [89]:
y_pred = classifier.predict(X_test)

In [90]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[137  14]
 [  8 141]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       151
           1       0.91      0.95      0.93       149

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

Accuracy: 0.9266666666666666
