In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("data_icaller.csv")

In [3]:
df.head()

phone  type  in_contact  duration  call_to  call_in  call_to_miss  \
0  84989082183   270          82       129        4        9            28   
1     8.42E+11  2105          29     42620      485       86           424   
2     8.43E+11  2019         102     44968      511      214           224   
3  84965303997   580          77      6106       57       26            85   
4  84979169738    23           9       455        1        5             0   

   call_in_miss  duration_call_to  duration_call_in  duration_call_to_miss  \
0            41                10               119                      0   
1            44             35170              4811                   2639   
2           102             27173             16562                   1233   
3            54               245              5852                      9   
4             3                97               358                      0   

   duration_call_in_miss  sum_call  Spam  Unnamed: 14  
0                      0        82     1          NaN  
1                      0      1039     1          NaN  
2                      0      1051     1          NaN  
3                      0       222     1          NaN  
4                      0         9     1          NaN

In [6]:
df=df.drop(["phone","duration_call_to","duration_call_in","duration_call_to_miss","duration_call_in_miss","sum_call"],axis=1)

In [7]:
df.head()

type  in_contact  duration  call_to  call_in  call_to_miss  call_in_miss  \
0   270          82       129        4        9            28            41   
1  2105          29     42620      485       86           424            44   
2  2019         102     44968      511      214           224           102   
3   580          77      6106       57       26            85            54   
4    23           9       455        1        5             0             3   

   Spam  Unnamed: 14  
0     1          NaN  
1     1          NaN  
2     1          NaN  
3     1          NaN  
4     1          NaN

In [9]:
df.shape

(1200, 9)

In [12]:
df.sum()

type              83134.0
in_contact         8579.0
duration        1105497.0
call_to           12205.0
call_in            8995.0
call_to_miss      12973.0
call_in_miss       3505.0
Spam                600.0
Unnamed: 14           0.0
dtype: float64

In [19]:
X = df.iloc[:, :-2].values

In [20]:
X

array([[  270,    82,   129, ...,     9,    28,    41],
       [ 2105,    29, 42620, ...,    86,   424,    44],
       [ 2019,   102, 44968, ...,   214,   224,   102],
       ...,
       [    2,     1,    45, ...,     1,     0,     0],
       [    1,     0,    19, ...,     0,     0,     0],
       [    6,     0,     0, ...,     0,     2,     0]], dtype=int64)

In [22]:
y = df.iloc[:, 7].values

In [23]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [26]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1], d

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [28]:
y_pred = classifier.predict(X_test)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[135  19]
 [ 24 122]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       154
           1       0.87      0.84      0.85       146

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300

Accuracy: 0.8566666666666667
